version: 1.2
workflows:
 - name: HMAS-QC-Pipeline2
   subclass: WDL
   primaryDescriptorPath: /workflows/hmas.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: HMAS-Mixed-Sites
   subclass: WDL
   primaryDescriptorPath: /workflows/mix_sites.wdl
   testParameterFiles:
    - /tests/inputs/empty.json